# Define Receiver Component
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

# Define Processor Component
processors:
  batch:
    timeout: 1s
  resource:
    attributes:
      - key: test.key
        value: "test-value"
        action: insert
  tail_sampling:
    decision_wait: 2s
    num_traces: 100
    expected_new_traces_per_sec: 1
    policies:
      [
        #{
        #    name: test-policy-1,
        #    type: status_code,
        #    status_code: {status_codes: [ERROR, UNSET]}
        # },
        # {
        #  name: test-policy-2,
        #  type: latency,
        #  latency: {threshold_ms: 1500}
        #}
      ]
# Define Exporter Component
exporters:
  #prometheus:
    #endpoint: "0.0.0.0:8889"
    #namespace: promexample
    #const_labels:
      #label1: value1
  logging:
    loglevel: error
  jaeger:
    endpoint: jaeger:14250
    insecure: true

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

#Tie Receiver, Processors and Exporter Components Via Service.
service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource,tail_sampling]
      exporters: [logging, jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]